# Generated by Django 4.1 on 2023-01-08 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNumber', models.IntegerField()),
                ('firstName', models.CharField(max_length=64)),
                ('middleName', models.CharField(blank=True, default='', max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('jobTitle', models.CharField(max_length=64)),
                ('streetAddress', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=32)),
                ('province', models.CharField(max_length=16)),
                ('postalCode', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=32)),
                ('hourlyWage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAccount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PayStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payPeriodStart', models.DateField()),
                ('payPeriodEnd', models.DateField()),
                ('payDate', models.DateField()),
                ('payFrequency', models.CharField(max_length=64)),
                ('payHours', models.FloatField()),
                ('regularPay', models.FloatField()),
                ('vacationPay', models.FloatField()),
                ('federalIncomeTax', models.FloatField()),
                ('provincialIncomeTax', models.FloatField()),
                ('ei', models.FloatField()),
                ('cpp', models.FloatField()),
                ('eiEmployer', models.FloatField()),
                ('cppEmployer', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='payrollAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.payrollaccount'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('payrollAccount', 'employeeNumber'), name='Unique Employee Constraint'),
        ),
    ]
